//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyApp.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FamilyApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dokumnent hinzufügen ähnelt.
        /// </summary>
        internal static string AddDocument {
            get {
                return ResourceManager.GetString("AddDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ausblenden ähnelt.
        /// </summary>
        internal static string AutoHidePanelToolTip {
            get {
                return ResourceManager.GetString("AutoHidePanelToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Leer ähnelt.
        /// </summary>
        internal static string CalendarNoneText {
            get {
                return ResourceManager.GetString("CalendarNoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Heute ähnelt.
        /// </summary>
        internal static string CalendarTodayText {
            get {
                return ResourceManager.GetString("CalendarTodayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ändern ähnelt.
        /// </summary>
        internal static string Changing {
            get {
                return ResourceManager.GetString("Changing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Löschen bestätigen ähnelt.
        /// </summary>
        internal static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Überschreiben von Datei bestätigen ähnelt.
        /// </summary>
        internal static string ConfirmOverWriteFile {
            get {
                return ResourceManager.GetString("ConfirmOverWriteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schwerer Fehler! Anwendung wird beendet! ähnelt.
        /// </summary>
        internal static string CriticalError {
            get {
                return ResourceManager.GetString("CriticalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Löschen ähnelt.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wollen Sie das Dokument &quot;#1&quot; wirklich löschen? ähnelt.
        /// </summary>
        internal static string DeleteFile {
            get {
                return ResourceManager.GetString("DeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soll der Ordner &apos;#1&apos; mit seinem gesamten Inhalt wirklich gelöscht werden? ähnelt.
        /// </summary>
        internal static string DeleteFolder {
            get {
                return ResourceManager.GetString("DeleteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wollen Sie die Gruppe &apos;#1&apos; wirklich löschen? ähnelt.
        /// </summary>
        internal static string DeleteGroup {
            get {
                return ResourceManager.GetString("DeleteGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wollen Sie die Gruppe oder den Nutzer &apos;#1&apos; wirklich löschen? ähnelt.
        /// </summary>
        internal static string DeleteGroupUser {
            get {
                return ResourceManager.GetString("DeleteGroupUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wollen Sie wirklich die Nachschlageliste löschen? ähnelt.
        /// </summary>
        internal static string DeleteLookUpList {
            get {
                return ResourceManager.GetString("DeleteLookUpList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wollen Sie den Datensatz wirklich löschen? ähnelt.
        /// </summary>
        internal static string DeleteRecord {
            get {
                return ResourceManager.GetString("DeleteRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wollen Sie die Tabelle wirklich löschen? ähnelt.
        /// </summary>
        internal static string DeleteTable {
            get {
                return ResourceManager.GetString("DeleteTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In der Tabelle befinden sich Datensätze!
        ///
        ///Wollen Sie die Tabelle trotzdem löschen? ähnelt.
        /// </summary>
        internal static string DeleteTableWithRecords {
            get {
                return ResourceManager.GetString("DeleteTableWithRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wollen Sie den Benutzer &apos;#1&apos; wirklich löschen? ähnelt.
        /// </summary>
        internal static string DeleteUser {
            get {
                return ResourceManager.GetString("DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wollen Sie die Filtermaske wirklich löschen? ähnelt.
        /// </summary>
        internal static string DeletMask {
            get {
                return ResourceManager.GetString("DeletMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wollen Sie die Filtermaske mit allen Unterelementen wirklich löschen? ähnelt.
        /// </summary>
        internal static string DeletMasks {
            get {
                return ResourceManager.GetString("DeletMasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sie besitzen keine Rechte für die &apos;#1&apos;
        ///
        ///
        ///Wenden Sie sich an den Administrator um Ihre Rechte ggf. zu ändern. ähnelt.
        /// </summary>
        internal static string DeviceRights {
            get {
                return ResourceManager.GetString("DeviceRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datei ist bereits von Nutzer &apos;#1&apos; auf Computer &apos;#2&apos; geöffnet! ähnelt.
        /// </summary>
        internal static string DocumentFileIsOpen {
            get {
                return ResourceManager.GetString("DocumentFileIsOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verzeichnis &apos;#1&apos; kann nicht gefunden werden! ähnelt.
        /// </summary>
        internal static string DocumentFolderIsInvalid {
            get {
                return ResourceManager.GetString("DocumentFolderIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abbrechen ähnelt.
        /// </summary>
        internal static string DropDownCancelButton {
            get {
                return ResourceManager.GetString("DropDownCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bearbeiten ähnelt.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tragen Sie den Name der Suchmaske ein! ähnelt.
        /// </summary>
        internal static string EditMask {
            get {
                return ResourceManager.GetString("EditMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ausführen/Sichtbar ähnelt.
        /// </summary>
        internal static string EditUser {
            get {
                return ResourceManager.GetString("EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einige Felder haben keine Werte!
        ///
        ///Solle die Eingabe verworfen werden? ähnelt.
        /// </summary>
        internal static string EmptyFields {
            get {
                return ResourceManager.GetString("EmptyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Endet mit Zeichenfolge ähnelt.
        /// </summary>
        internal static string EndetMitZeichenfolge {
            get {
                return ResourceManager.GetString("EndetMitZeichenfolge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler ähnelt.
        /// </summary>
        internal static string ErrorString {
            get {
                return ResourceManager.GetString("ErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ausführen/Sichtbar ähnelt.
        /// </summary>
        internal static string Execute {
            get {
                return ResourceManager.GetString("Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Feld ist bereits vorhanden! ähnelt.
        /// </summary>
        internal static string FieldExists {
            get {
                return ResourceManager.GetString("FieldExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dokumente (*.txt;*.doc;*.xls;*.PDF)|*.txt;*.doc;*.xls;*.PDF|Vorlagen (*.dot;*.xlt)|*.dot;*.xlt|Bilddateien (*.BMP;*.JPG;*.JPEG;*.JPE;*.JFIF;*.PNG;*.TIF;*.TIFF;*.GIF)|*.BMP;*.JPG;*.JPEG;*.JPE;*.JFIF;*.PNG;*.TIF;*.TIFF;*.GIF|Alle Dateien|*.* ähnelt.
        /// </summary>
        internal static string FileFilter {
            get {
                return ResourceManager.GetString("FileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datei wurde erfolgreich eingecheckt! ähnelt.
        /// </summary>
        internal static string FileIsCheckIn {
            get {
                return ResourceManager.GetString("FileIsCheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Datei &apos;#1&apos; wurder erfolgreich nach &apos;#2&apos; kopiert bzw. ausgecheckt! ähnelt.
        /// </summary>
        internal static string FileWasSuccCheckOut {
            get {
                return ResourceManager.GetString("FileWasSuccCheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Microsoft Word (*.doc)|*.doc|Microsoft Excel (*.xls)|*.xls|Acrobat (*.pdf)|*.pdf|Alle Dateien (*.*)|*.* ähnelt.
        /// </summary>
        internal static string Filter1 {
            get {
                return ResourceManager.GetString("Filter1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beginnt mit Zeichenfolge ähnelt.
        /// </summary>
        internal static string FilterRowConditionBeginsWith {
            get {
                return ResourceManager.GetString("FilterRowConditionBeginsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filter löschen ähnelt.
        /// </summary>
        internal static string FilterRowConditionClear {
            get {
                return ResourceManager.GetString("FilterRowConditionClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In Zeichenfolge enthalten ähnelt.
        /// </summary>
        internal static string FilterRowConditionContains {
            get {
                return ResourceManager.GetString("FilterRowConditionContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gleich ähnelt.
        /// </summary>
        internal static string FilterRowConditionEqual {
            get {
                return ResourceManager.GetString("FilterRowConditionEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Größer als ähnelt.
        /// </summary>
        internal static string FilterRowConditionGreaterThan {
            get {
                return ResourceManager.GetString("FilterRowConditionGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Größer oder gleich ähnelt.
        /// </summary>
        internal static string FilterRowConditionGreaterThanOrEqual {
            get {
                return ResourceManager.GetString("FilterRowConditionGreaterThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Leer ähnelt.
        /// </summary>
        internal static string FilterRowConditionIsEmpty {
            get {
                return ResourceManager.GetString("FilterRowConditionIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kleiner als ähnelt.
        /// </summary>
        internal static string FilterRowConditionLessThan {
            get {
                return ResourceManager.GetString("FilterRowConditionLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kleiner oder gleich ähnelt.
        /// </summary>
        internal static string FilterRowConditionLessThanOrEqual {
            get {
                return ResourceManager.GetString("FilterRowConditionLessThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nicht in Zeichenfolge enthalten ähnelt.
        /// </summary>
        internal static string FilterRowConditionNotContains {
            get {
                return ResourceManager.GetString("FilterRowConditionNotContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nicht gleich ähnelt.
        /// </summary>
        internal static string FilterRowConditionNotEqual {
            get {
                return ResourceManager.GetString("FilterRowConditionNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nicht leer ähnelt.
        /// </summary>
        internal static string FilterRowConditionNotIsEmpty {
            get {
                return ResourceManager.GetString("FilterRowConditionNotIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filter ähnelt.
        /// </summary>
        internal static string FilterRowInfoText {
            get {
                return ResourceManager.GetString("FilterRowInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dieser Ordername ist unter dem gleichen Namen bereits vorhanden! ähnelt.
        /// </summary>
        internal static string FolderNameExists {
            get {
                return ResourceManager.GetString("FolderNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vollzugriff ähnelt.
        /// </summary>
        internal static string FullAccess {
            get {
                return ResourceManager.GetString("FullAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ziehen Sie einen Spaltenkopf in diesen Bereich, um eine Spalte zu gruppieren ähnelt.
        /// </summary>
        internal static string GroupByBoxInfoText {
            get {
                return ResourceManager.GetString("GroupByBoxInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gruppe ist bereits vorhanden! ähnelt.
        /// </summary>
        internal static string GroupExists {
            get {
                return ResourceManager.GetString("GroupExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_augen_emoji_16 {
            get {
                object obj = ResourceManager.GetObject("icons8-augen-emoji-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_in_ordner_kopieren_16 {
            get {
                object obj = ResourceManager.GetObject("icons8-in-ordner-kopieren-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_microsoft_excel_2019_color_16 {
            get {
                object obj = ResourceManager.GetObject("icons8-microsoft-excel-2019-color-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_microsoft_word_2019_color_16 {
            get {
                object obj = ResourceManager.GetObject("icons8-microsoft-word-2019-color-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Information ähnelt.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Geben Sie einen Namen von maximal 50 Zeichen ein! ähnelt.
        /// </summary>
        internal static string InputLookUpName {
            get {
                return ResourceManager.GetString("InputLookUpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einfügen ähnelt.
        /// </summary>
        internal static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ist ein ungültiges Zeichen! ähnelt.
        /// </summary>
        internal static string InvalidChar {
            get {
                return ResourceManager.GetString("InvalidChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Am Anfang von Datenbankfeldern dürfen keine nummerischen Werte vorkommen! ähnelt.
        /// </summary>
        internal static string InvalidCharByNumber {
            get {
                return ResourceManager.GetString("InvalidCharByNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die INFO: Sie sind nicht der Besitzer von diesem Dokumente das Sie gerade löschen wollen! ähnelt.
        /// </summary>
        internal static string InvalidDocumentOwnerToDelete {
            get {
                return ResourceManager.GetString("InvalidDocumentOwnerToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der eingegebene Feldname ist ein reserviertes Schlüsselwort. Bitte verwenden Sie eine andere Bezeichnung! ähnelt.
        /// </summary>
        internal static string InvalidFieldName {
            get {
                return ResourceManager.GetString("InvalidFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die INFO: Sie sind nicht der Besitzer von diesem Ordner den Sie gerade löschen wollen! ähnelt.
        /// </summary>
        internal static string InvalidFolderOwnerToDelete {
            get {
                return ResourceManager.GetString("InvalidFolderOwnerToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ungültige Anmeldeinformationen ähnelt.
        /// </summary>
        internal static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eintrag bereits vorhanden ähnelt.
        /// </summary>
        internal static string ItemExists {
            get {
                return ResourceManager.GetString("ItemExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Listenname ähnelt.
        /// </summary>
        internal static string ListName {
            get {
                return ResourceManager.GetString("ListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sie besitzen keine Rechte für den ausgewählten Standort &apos;#1&apos; ähnelt.
        /// </summary>
        internal static string LocationRights {
            get {
                return ResourceManager.GetString("LocationRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nachschlageliste ähnelt.
        /// </summary>
        internal static string LookUpList {
            get {
                return ResourceManager.GetString("LookUpList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Nachschlageliste &apos;#1&apos; existiert bereits! ähnelt.
        /// </summary>
        internal static string LookUpListExists {
            get {
                return ResourceManager.GetString("LookUpListExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Nachschlageliste wird von anderen Tabellen verwendet und kann nicht gelöscht werden! 
        ///
        ///Sie müssen zuerst alle Verweise dieser Liste entfernen! ähnelt.
        /// </summary>
        internal static string LookUpListInUse {
            get {
                return ResourceManager.GetString("LookUpListInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Nachschlageliste &apos;#1&apos;&apos; wurde erfolgreich gespeichert! ähnelt.
        /// </summary>
        internal static string LookUpListSaved {
            get {
                return ResourceManager.GetString("LookUpListSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Abbrechen ähnelt.
        /// </summary>
        internal static string MsgButtonTextCancel {
            get {
                return ResourceManager.GetString("MsgButtonTextCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Kopieren ähnelt.
        /// </summary>
        internal static string MsgButtonTextCopy {
            get {
                return ResourceManager.GetString("MsgButtonTextCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Löschen ähnelt.
        /// </summary>
        internal static string MsgButtonTextDelete {
            get {
                return ResourceManager.GetString("MsgButtonTextDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Neuanlage ähnelt.
        /// </summary>
        internal static string MsgButtonTextNewDoc {
            get {
                return ResourceManager.GetString("MsgButtonTextNewDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Nein ähnelt.
        /// </summary>
        internal static string MsgButtonTextNo {
            get {
                return ResourceManager.GetString("MsgButtonTextNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Ja ähnelt.
        /// </summary>
        internal static string MsgButtonTextYes {
            get {
                return ResourceManager.GetString("MsgButtonTextYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wollen Sie den Datensatz wirklich löschen? ähnelt.
        /// </summary>
        internal static string MsgDeleteRecord {
            get {
                return ResourceManager.GetString("MsgDeleteRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Löschen &amp;ohne Unterelemente ähnelt.
        /// </summary>
        internal static string MsgDeleteWithoutSubElements {
            get {
                return ResourceManager.GetString("MsgDeleteWithoutSubElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Löschen &amp;mit Unterelemente ähnelt.
        /// </summary>
        internal static string MsgDeleteWithSubElements {
            get {
                return ResourceManager.GetString("MsgDeleteWithSubElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datensatz konnter nicht wiederhergestellt werden! ähnelt.
        /// </summary>
        internal static string MsgNonSuccUndo {
            get {
                return ResourceManager.GetString("MsgNonSuccUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datensatz aktualisieren ähnelt.
        /// </summary>
        internal static string MsgRefreshData {
            get {
                return ResourceManager.GetString("MsgRefreshData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datensatz wurde erfolgreich wiederhergestellt! ähnelt.
        /// </summary>
        internal static string MsgSuccUndo {
            get {
                return ResourceManager.GetString("MsgSuccUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Löschen bestätigen ähnelt.
        /// </summary>
        internal static string MsgTitleConfirmDelete {
            get {
                return ResourceManager.GetString("MsgTitleConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ist bereits vorhanden! ähnelt.
        /// </summary>
        internal static string NameExists {
            get {
                return ResourceManager.GetString("NameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neuer Order ähnelt.
        /// </summary>
        internal static string NewFolder {
            get {
                return ResourceManager.GetString("NewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neue Gruppe ähnelt.
        /// </summary>
        internal static string NewGroup {
            get {
                return ResourceManager.GetString("NewGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tragen Sie den Name der neuen Suchmaske ein! ähnelt.
        /// </summary>
        internal static string NewMask {
            get {
                return ResourceManager.GetString("NewMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neuer Status ähnelt.
        /// </summary>
        internal static string NewStatus {
            get {
                return ResourceManager.GetString("NewStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tragen Sie den Namen des neuen Statuses im Eingabefeld ein! ähnelt.
        /// </summary>
        internal static string NewStatusPrompt {
            get {
                return ResourceManager.GetString("NewStatusPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ein Element kann nicht in eine ihr selbst untegeordnete Gruppe verschoben werden! ähnelt.
        /// </summary>
        internal static string NodeItemHasChildrenByCopy {
            get {
                return ResourceManager.GetString("NodeItemHasChildrenByCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte selektieren Sie ein Feld in der linken Spalte! ähnelt.
        /// </summary>
        internal static string NonFieldSelect {
            get {
                return ResourceManager.GetString("NonFieldSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte wählen Sie einen Standort aus! ähnelt.
        /// </summary>
        internal static string NonSite {
            get {
                return ResourceManager.GetString("NonSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passwort konnte nicht bestätigt werden! ähnelt.
        /// </summary>
        internal static string NotConfirmPassword {
            get {
                return ResourceManager.GetString("NotConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Drüber hinaus ähnelt.
        /// </summary>
        internal static string OutlookDateBeyondNextMonth {
            get {
                return ResourceManager.GetString("OutlookDateBeyondNextMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vor einem Monat ähnelt.
        /// </summary>
        internal static string OutlookDateEarlierThisMonth {
            get {
                return ResourceManager.GetString("OutlookDateEarlierThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Leer ähnelt.
        /// </summary>
        internal static string OutlookDateEmpty {
            get {
                return ResourceManager.GetString("OutlookDateEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Letzten Monat ähnelt.
        /// </summary>
        internal static string OutlookDateLastMonth {
            get {
                return ResourceManager.GetString("OutlookDateLastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Letzte Woche ähnelt.
        /// </summary>
        internal static string OutlookDateLastWeek {
            get {
                return ResourceManager.GetString("OutlookDateLastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Älter als diesen Monat ähnelt.
        /// </summary>
        internal static string OutlookDateLaterThisMonth {
            get {
                return ResourceManager.GetString("OutlookDateLaterThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nächster Monat ähnelt.
        /// </summary>
        internal static string OutlookDateNextMonth {
            get {
                return ResourceManager.GetString("OutlookDateNextMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nächste Woche ähnelt.
        /// </summary>
        internal static string OutlookDateNextWeek {
            get {
                return ResourceManager.GetString("OutlookDateNextWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Älter ähnelt.
        /// </summary>
        internal static string OutlookDateOlder {
            get {
                return ResourceManager.GetString("OutlookDateOlder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vorvorletzte Woche ähnelt.
        /// </summary>
        internal static string OutlookDateThreeWeeksAgo {
            get {
                return ResourceManager.GetString("OutlookDateThreeWeeksAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In drei Wochen ähnelt.
        /// </summary>
        internal static string OutlookDateThreeWeeksAway {
            get {
                return ResourceManager.GetString("OutlookDateThreeWeeksAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Heute ähnelt.
        /// </summary>
        internal static string OutlookDateToday {
            get {
                return ResourceManager.GetString("OutlookDateToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Morgen ähnelt.
        /// </summary>
        internal static string OutlookDateTomorrow {
            get {
                return ResourceManager.GetString("OutlookDateTomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vor zwei Wochen ähnelt.
        /// </summary>
        internal static string OutlookDateTwoWeeksAgo {
            get {
                return ResourceManager.GetString("OutlookDateTwoWeeksAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In zwei Wochen ähnelt.
        /// </summary>
        internal static string OutlookDateTwoWeeksAway {
            get {
                return ResourceManager.GetString("OutlookDateTwoWeeksAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gestern ähnelt.
        /// </summary>
        internal static string OutlookDateYesterday {
            get {
                return ResourceManager.GetString("OutlookDateYesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Datei &apos;#1&apos; ist bereits vorhanden! ähnelt.
        /// </summary>
        internal static string OverWriteFile {
            get {
                return ResourceManager.GetString("OverWriteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passwort ist bereits vorhanden! ähnelt.
        /// </summary>
        internal static string PasswordExists {
            get {
                return ResourceManager.GetString("PasswordExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Drucken ähnelt.
        /// </summary>
        internal static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lesen ähnelt.
        /// </summary>
        internal static string Read {
            get {
                return ResourceManager.GetString("Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lesen / Ausführen / Löschen ähnelt.
        /// </summary>
        internal static string ReadExecuting {
            get {
                return ResourceManager.GetString("ReadExecuting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zum angegebenen Datensatz konnte nicht gewechselt werden! ähnelt.
        /// </summary>
        internal static string RecordNavigatorError {
            get {
                return ResourceManager.GetString("RecordNavigatorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datensatz:|von ähnelt.
        /// </summary>
        internal static string RecordNavigatorString {
            get {
                return ResourceManager.GetString("RecordNavigatorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datensatz wirklich unwiederruflich löschen? ähnelt.
        /// </summary>
        internal static string RecordReallyDeleteIrrevocably {
            get {
                return ResourceManager.GetString("RecordReallyDeleteIrrevocably", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ordner umbenennen. ähnelt.
        /// </summary>
        internal static string RenameFolder {
            get {
                return ResourceManager.GetString("RenameFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gruppe umbenennen ähnelt.
        /// </summary>
        internal static string RenameGroup {
            get {
                return ResourceManager.GetString("RenameGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filtermasken ähnelt.
        /// </summary>
        internal static string SearchMasks {
            get {
                return ResourceManager.GetString("SearchMasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dokumentenstatus ändern ähnelt.
        /// </summary>
        internal static string StateChange {
            get {
                return ResourceManager.GetString("StateChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tabelle ist bereits vorhanden! ähnelt.
        /// </summary>
        internal static string TableExists {
            get {
                return ResourceManager.GetString("TableExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tabellenname ähnelt.
        /// </summary>
        internal static string TableName {
            get {
                return ResourceManager.GetString("TableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Tabellenname &apos;#1&apos; existiert bereits! ähnelt.
        /// </summary>
        internal static string TableNameExists {
            get {
                return ResourceManager.GetString("TableNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tesdt ähnelt.
        /// </summary>
        internal static string Tesdt {
            get {
                return ResourceManager.GetString("Tesdt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Heute ähnelt.
        /// </summary>
        internal static string ToDay {
            get {
                return ResourceManager.GetString("ToDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Benutzerverwaltung ähnelt.
        /// </summary>
        internal static string UM {
            get {
                return ResourceManager.GetString("UM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unerwarteter Fehler ähnelt.
        /// </summary>
        internal static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Benutzername ähnelt.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Wert &apos;#1&apos; wird bereits verwendet!
        ///
        ///Wollen Sie den Eintrag trotzdem löschen? ähnelt.
        /// </summary>
        internal static string ValueExists {
            get {
                return ResourceManager.GetString("ValueExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Im Feld &apos;#1&apos; fehlt Ihre Eingabe! ähnelt.
        /// </summary>
        internal static string ValueIsMissing {
            get {
                return ResourceManager.GetString("ValueIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Wert &apos;#1&apos; existiert bereits!
        ///Die Einträge in einer Werteliste müssen eindeutig sein! ähnelt.
        /// </summary>
        internal static string ValueIsNotUnique {
            get {
                return ResourceManager.GetString("ValueIsNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Werteliste ähnelt.
        /// </summary>
        internal static string ValueList {
            get {
                return ResourceManager.GetString("ValueList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Werteliste &apos;#1&apos; wird bereits in anderen Tabellen verwendet! ähnelt.
        /// </summary>
        internal static string ValueListInUse {
            get {
                return ResourceManager.GetString("ValueListInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ordnerinhalt anzeigen ähnelt.
        /// </summary>
        internal static string ViewFolderContens {
            get {
                return ResourceManager.GetString("ViewFolderContens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schreiben ähnelt.
        /// </summary>
        internal static string Write {
            get {
                return ResourceManager.GetString("Write", resourceCulture);
            }
        }
    }
}
