//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArbeitsStunden
    {
        public int ID { get; set; }
        public System.DateTime Datum { get; set; }
        public int UserID { get; set; }
        public decimal Stunden { get; set; }
        public string Taetigkeit { get; set; }
    
        public virtual Bearbeiter Bearbeiter { get; set; }
    }
}
