//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_DocumenState
    {
        public int ID { get; set; }
        public bool FontStrikeThru { get; set; }
        public Nullable<int> ForeColor { get; set; }
        public string EndText { get; set; }
        public bool UsesBackColor { get; set; }
        public Nullable<int> BackColor { get; set; }
        public Nullable<int> FLAG { get; set; }
        public string BeginText { get; set; }
        public bool FontItalic { get; set; }
        public string Description { get; set; }
        public bool FontUnderline { get; set; }
        public string FontName { get; set; }
        public bool FontBold { get; set; }
        public string StatusName { get; set; }
        public Nullable<int> FontSize { get; set; }
        public Nullable<int> UsesDateEnd { get; set; }
        public Nullable<int> UsesDateBegin { get; set; }
    }
}
