//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_Documents
    {
        public int ID { get; set; }
        public Nullable<int> FolderID { get; set; }
        public byte[] Document { get; set; }
        public string DocumentType { get; set; }
        public string Description { get; set; }
        public Nullable<int> FLAG { get; set; }
        public Nullable<int> DocumentState { get; set; }
        public byte[] ICON { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
        public Nullable<long> FileSize { get; set; }
    
        public virtual DM_Folders DM_Folders { get; set; }
    }
}
