//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_Folders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DM_Folders()
        {
            this.DM_Documents = new HashSet<DM_Documents>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> FLAG { get; set; }
        public string FolderName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DM_Documents> DM_Documents { get; set; }
    }
}
