//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Password
    {
        public int ID { get; set; }
        public Nullable<int> PasswordTreeID { get; set; }
        public string FactoryName { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public string Homepage { get; set; }
        public string Remark { get; set; }
    
        public virtual PasswordTree PasswordTree { get; set; }
    }
}
