//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_Reg
    {
        public int ID { get; set; }
        public string REG_SETTINGS { get; set; }
        public Nullable<int> REG_TYPE { get; set; }
        public string REG_ROOT { get; set; }
        public string REG_KEY { get; set; }
        public string REG_SECTION { get; set; }
        public byte[] REG_BLOB { get; set; }
        public string ModificationUser { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
    }
}
